http:
  port: "8081"
  
american:
  host: "training4-american--proxy-td.us-e2.cloudhub.io"
  port: "80"
  protocol: "HTTP"
  client_id:  "69c8824c35944f509755f3371f02ab39"
  client_secret:  "2Da5839d14074192888A9AcA64639aa5"
 
training:
  host: "mu.learn.mulesoft.com"
  port: "80"
  basepath: "/"
  protocol: "HTTP"
  
delta:
  wsdl: "http://mu.learn.mulesoft.com/delta?wsdl"
  service: "TicketServiceService"
  port: "TicketServicePort" 
  